# Working with Arrays

In [1]:
import numpy as np

## Slicing

In [2]:
matrix_A = np.array([[1,2,3], [4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing

In [3]:
matrix_A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
type(matrix_A[:,:])

numpy.ndarray

In [5]:
matrix_A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
matrix_A[1]

array([4, 5, 6])

In [7]:
matrix_A[:-1]

array([[1, 2, 3]])

In [8]:
matrix_A[:,1:]

array([[2, 3],
       [5, 6]])

In [9]:
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
matrix_A[1:,1:]

array([[5, 6]])

### Stepwise Slicing

In [11]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [12]:
matrix_B[-1::-1,::2]

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

### Conditional Slicing

In [13]:
matrix_C = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [14]:
matrix_C[:,0]

array([1, 3, 4])

In [15]:
matrix_C[:,0] > 2

array([False,  True,  True])

In [16]:
matrix_C[:,:] > 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [17]:
matrix_C[matrix_C[:,:] % 2 == 0]

array([2, 0, 6, 6, 4, 4, 8, 0])

In [18]:
matrix_C[(matrix_C[:,:] % 2 == 0) | (matrix_C[:,:] <= 4)]

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])

## Dimensions and the Squeeze Function

In [20]:
matrix_D = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [21]:
type(matrix_D[0,0])

numpy.int64

In [22]:
print(matrix_D[0,0])

1


In [23]:
type(matrix_D[0,0:1])

numpy.ndarray

In [24]:
print(matrix_D[0,0:1])

[1]


In [25]:
type(matrix_D[0:1,0:1])

numpy.ndarray

In [26]:
print(matrix_D[0:1,0:1])

[[1]]


In [27]:
print(matrix_D[0,0].shape)
print(matrix_D[0,0:1].shape)
print(matrix_D[0:1,0:1].shape)

()
(1,)
(1, 1)


In [28]:
print(matrix_D[0:1,0:1].squeeze())

1


In [29]:
np.squeeze(matrix_D[0:1,0:1])

array(1)

In [30]:
print(matrix_D[0,0].squeeze().shape)
print(matrix_D[0,0:1].squeeze().shape)
print(matrix_D[0:1,0:1].squeeze().shape)

()
()
()
