# Introduction to NumPy

## Installing & Updating the Package

NumPy comes pre-isntalled if you're using Anaconda. 
**pip install numpy** 

To get the latest version:
**pip install numpy --upgrade**

### Importing NumPy

In [1]:
import numpy as np

### Using NumPy

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
array_b = np.array([[1,2,3], [4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

### NumPy Documentation

https://numpy.org/devdocs/ <- <i> A link to the NumPy documentation

In [5]:
np.mean(array_b, axis = 0)

array([2.5, 3.5, 4.5])