# NumPy DataTypes

In [1]:
import numpy as np

### Ndarrays

In [2]:
array_a = np.array([1,2,3])

In [3]:
print(array_a)

[1 2 3]


In [4]:
type(array_a)

numpy.ndarray

In [5]:
array_a.shape

(3,)

In [6]:
array_b = np.array([[7,8,9,], [10,11,12]])

In [7]:
type(array_b)

numpy.ndarray

In [8]:
array_b.shape

(2, 3)

In [9]:
array_c = np.array(13)

In [10]:
type(array_c)

numpy.ndarray

In [11]:
print(array_c)

13


In [12]:
array_c.shape

()

In [13]:
array_d = np.array([15])

In [14]:
type(array_d)

numpy.ndarray

In [15]:
print(array_d)

[15]


In [16]:
array_d.shape

(1,)

In [17]:
array_e = np.array([[15]])
array_e

array([[15]])

### List vs Array

In [18]:
list_a = [[1,2,3], [4,5,6]]

In [19]:
len(list_a)

2

In [20]:
array_a = np.array(list_a)

In [21]:
type(list_a)

list

In [22]:
type(array_a)

numpy.ndarray

In [24]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [25]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [26]:
array_a.shape

(2, 3)

In [27]:
len(list_a[1])

3

In [28]:
list_a

[[1, 2, 3], [4, 5, 6]]

In [29]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [31]:
print(list_b)

[1, 2, 3, 4, 5, 6]


In [32]:
print(array_b)

[5 7 9]


In [33]:
import math
array_e = math.sqrt(array_a[1,0])
print(array_e)

2.0


In [34]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### String vs Object vs Numbers

In [35]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv",
                              delimiter = ',',
                              dtype = np.int32,
                              #dtype = np.float16
                              #dtype = np.str
                              #dtype = np.object
                              #dtype = (np.int32, np.str, np.str, np.str, np.str, np.str, np.int32)
                              )
print(lending_co_lt)

[[   -1    -1    -1 ...    -1    -1    -1]
 [    1    -1    -1 ...    -1    -1 16600]
 [    2    -1    -1 ...    -1    -1 16600]
 ...
 [ 1041    -1    -1 ...    -1    -1 16600]
 [ 1042    -1    -1 ...    -1    -1 15600]
 [ 1043    -1    -1 ...    -1    -1 16600]]


In [36]:
lending_co_lt[0,0] + lending_co_lt[0,1]

-2